# -*- coding: utf-8 -*-
"""Spam Email Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10p1ckc2lRWax9igeMUAm5DM_xcGfJMRt

Importing libraries
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

"""Load dataset"""

url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

df = pd.read_csv(url, sep='\t', names=["label", "message"])

print("Dataset Preview:\n")
print(df.head())

# ================================
# DATA PREPROCESSING
# ================================

# Convert labels: ham = 0, spam = 1
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

# ================================
# SPLIT DATA
# ================================
X = df['message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ================================
# TEXT VECTORIZATION
# ================================
vectorizer = CountVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# ================================
# MODEL TRAINING
# ================================
model = MultinomialNB()
model.fit(X_train_vec, y_train)

# ================================
# PREDICTION
# ================================
y_pred = model.predict(X_test_vec)

# ================================
# EVALUATION
# ================================
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# ================================
# TEST WITH CUSTOM MESSAGE
# ================================
sample = ["Congratulations! You have won a free lottery ticket"]
sample_vec = vectorizer.transform(sample)

prediction = model.predict(sample_vec)

if prediction[0] == 1:
    print("\nThis message is SPAM 🚨")
else:
    print("\nThis message is NOT SPAM ✅")