# -*- coding: utf-8 -*-
"""Breast Cancer Diagnosis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3Vb684bKVjBRZIhp8Hhkwr4tsPQ44Wp
"""

# ================================
# IMPORT LIBRARIES
# ================================
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.linear_model import LogisticRegression

# ================================
# LOAD DATASET
# ================================
data = load_breast_cancer()

df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

print("Dataset Preview:\n")
print(df.head())

# ================================
# SPLIT DATA
# ================================
X = df.drop('target', axis=1)
y = df['target']

# ================================
# FEATURE SCALING
# ================================
scaler = StandardScaler()
X = scaler.fit_transform(X)

# ================================
# TRAIN TEST SPLIT
# ================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ================================
# MODEL TRAINING
# ================================
model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

# ================================
# PREDICTION
# ================================
y_pred = model.predict(X_test)

# ================================
# EVALUATION
# ================================
print("\nAccuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))