# -*- coding: utf-8 -*-
"""Credit Risk Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TknojWB_JAoo0WWldf3Mms4pfKgNTTba
"""

# ================================
# IMPORT LIBRARIES
# ================================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.linear_model import LogisticRegression

# ================================
# LOAD DATASET (ONLINE)
# ================================
df = pd.read_csv('train (2).csv')
print("Dataset Preview:\n")
print(df.head())

# ================================
# DATA PREPROCESSING
# ================================

# Drop irrelevant column
df = df.drop('Loan_ID', axis=1)

# Handle missing values
df = df.dropna()

# Encode categorical variables
le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

print("\nAfter Encoding:\n")
print(df.head())

# ================================
# SPLIT DATA
# ================================
X = df.drop('Loan_Status', axis=1)
y = df['Loan_Status']

# ================================
# FEATURE SCALING
# ================================
scaler = StandardScaler()
X = scaler.fit_transform(X)

# ================================
# TRAIN TEST SPLIT
# ================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ================================
# MODEL TRAINING
# ================================
model = LogisticRegression()
model.fit(X_train, y_train)

# ================================
# PREDICTION
# ================================
y_pred = model.predict(X_test)

# ================================
# EVALUATION
# ================================
print("\nAccuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))