# -*- coding: utf-8 -*-
"""Anomaly Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdAXOry-pxR79KYGbiOjhNf3am3Yz53H
"""

# ================================
# IMPORT LIBRARIES
# ================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import IsolationForest

# ================================
# CREATE SAMPLE DATA
# ================================
np.random.seed(42)

# Normal data
normal_data = np.random.normal(loc=50, scale=5, size=200)

# Anomalies (fraud-like)
anomalies = np.random.normal(loc=80, scale=2, size=10)

data = np.concatenate([normal_data, anomalies])

df = pd.DataFrame(data, columns=['Transaction_Amount'])

print(df.head())

# ================================
# MODEL (ISOLATION FOREST)
# ================================
model = IsolationForest(contamination=0.05)

df['Anomaly'] = model.fit_predict(df)

# Convert output:
# -1 → anomaly
#  1 → normal
df['Anomaly'] = df['Anomaly'].map({1: 0, -1: 1})

print("\nDetected Anomalies:\n")
print(df[df['Anomaly'] == 1])

# ================================
# VISUALIZATION
# ================================
plt.figure()

plt.scatter(df.index, df['Transaction_Amount'], label='Normal')
plt.scatter(df[df['Anomaly']==1].index,
            df[df['Anomaly']==1]['Transaction_Amount'],
            label='Anomaly')

plt.xlabel("Index")
plt.ylabel("Transaction Amount")
plt.title("Anomaly Detection using Isolation Forest")
plt.legend()

plt.show()