# -*- coding: utf-8 -*-
"""Disease Diagnosis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UM3eBiYBnH7ZAyXGFDf33UOLhWmJ0N33
"""

# ================================
# IMPORT LIBRARIES
# ================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# ================================
# LOAD DATASET
# ================================
data = load_breast_cancer()

df = pd.DataFrame(data.data, columns=data.feature_names)

print("Dataset Preview:\n")
print(df.head())

# ================================
# FEATURE SCALING
# ================================
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

# ================================
# FIND OPTIMAL CLUSTERS (ELBOW)
# ================================
wcss = []

for i in range(1, 10):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

# Plot Elbow Graph
plt.plot(range(1, 10), wcss)
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.title("Elbow Method")
plt.show()

# ================================
# APPLY K-MEANS
# ================================
kmeans = KMeans(n_clusters=2, random_state=42)
clusters = kmeans.fit_predict(X_scaled)

df['Cluster'] = clusters

print("\nClustered Data:\n")
print(df.head())

# ================================
# VISUALIZATION (2 FEATURES)
# ================================
plt.scatter(df.iloc[:, 0], df.iloc[:, 1], c=clusters)
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("Disease Clustering")
plt.show()