# -*- coding: utf-8 -*-
"""Data_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nIfvnUL2NT6wUXc8qnng_0zVXgA5kB_8
"""

#import libraries
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

"""Creating Dataset"""

data = {
    "Country": ["India", "USA", "France", "India", "USA", "France", "India", "USA"],
    "Age": [25, np.nan, 35, 40, np.nan, 30, 28, 50],
    "Salary": [50000, 60000, np.nan, 80000, 75000, np.nan, 52000, 90000],
    "Gender": ["Male", "Female", "Female", "Male", "Female", "Male", "Male", "Female"],
    "Purchased": ["No", "Yes", "No", "Yes", "Yes", "No", "Yes", "No"]
}

df = pd.DataFrame(data)

print("Original Dataset:\n", df)

"""Handling Missing Values"""

imputer = SimpleImputer(strategy='mean')
df[['Age', 'Salary']] = imputer.fit_transform(df[['Age', 'Salary']])

print("\nAfter Missing Value Handling:\n", df)

"""Removing duplicates"""

df = df.drop_duplicates()
print("\nAfter Removing Duplicates:\n", df)

"""ENCODE CATEGORICAL VARIABLES"""

# Label Encoding (binary column)
label_encoder = LabelEncoder()
df['Purchased'] = label_encoder.fit_transform(df['Purchased'])

# One-Hot Encoding (multiple categories)
df = pd.get_dummies(df, columns=['Country', 'Gender'])

print("\nAfter Encoding:\n", df)

"""Outlier Handling"""

def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return df[(df[column] >= lower) & (df[column] <= upper)]

df = remove_outliers(df, 'Salary')

print("\nAfter Outlier Removal:\n", df)

"""Feature Scaling"""

scaler = StandardScaler()
df[['Age', 'Salary']] = scaler.fit_transform(df[['Age', 'Salary']])

# OR Normalization (alternative)
# minmax = MinMaxScaler()
# df[['Age', 'Salary']] = minmax.fit_transform(df[['Age', 'Salary']])

print("\nAfter Scaling:\n", df)

"""Feature Engineering"""

# Example: Create Age Group
df['Age_Group'] = pd.cut(df['Age'], bins=3, labels=["Young", "Middle", "Senior"])

# Encode new feature
df = pd.get_dummies(df, columns=['Age_Group'])

print("\nAfter Feature Engineering:\n", df)

"""Split Dataset"""

X = df.drop('Purchased', axis=1)
y = df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("\nTrain Shape:", X_train.shape)
print("Test Shape:", X_test.shape)